version: "3.4"

services:
  postgres-db:
    container_name: postgres
    image: library/postgres:alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
    - "5432:5432"

  loan-system-api:
    container_name: loan-system-api
    build:
      context: .
    image: loan-system-api
    depends_on:
      - postgres-db
    ports:
    - "8090:8090"
